### ISSUE TITLE
Server subscription sends deprecated Property EventType deprecated in EventService v1_3_0+

### ISSUE THREAD

**Issue by bscriv** [DMTF/Redfish-Event-Listener#10]
The subscription function attempts to send property EventType, which was deprecated in EventService v1_3_0, so may cause the request to fail on DSP0266 version 1.6.0 compliant servers.

```
def PerformSubscription():
    global ServerIPs, UserNames, Passwords, Destination, EventTypes, ContextDetail, Protocol, SubscriptionURI, verbose
    ServerIPList = [x for x in ServerIPs.split(",") if x.strip() != '']
    UserNameList = UserNames.split(",")
    PasswordList = Passwords.split(",")
    AttributeNameList = ['Destination', 'EventTypes', 'Context', 'Protocol']
    AttributeValueList = [Destination, EventTypes, ContextDetail, Protocol]
```

> {"@Message.ExtendedInfo":[{"MessageArgs":["EventTypes"],"Resolution":"Remove the unknown property from the request body and resubmit the request if the operation failed.","MessageId":"Base.1.6.PropertyUnknown","Severity":"Warning","Message":"The property EventTypes is not in the list of valid properties for the resource.","@odata.type":"#Message.v1_0_8.Message"}]

**Comment by frsauvage** [comment]
Same problem,

**Comment by tomasg2012** [comment]
Is this on the `dev` branch?  Please update your copy of redfish/tacklebox for your tool's environment, a small change with that library now allows subscriptions without EventTypes in the payload.

Does this occur when omitting EventTypes from the configuration, or is it still present?

**Comment by frsauvage** [comment]
Hi,
master branch.
I tried with 
EventTypes = Alert
EventTypes = "Alert"
EventTypes = ["Alert", "ResourceAdded"]
I got always an issue : Subscription is not successful.

Then I removed :
![image](https://user-images.githubusercontent.com/23147820/154960237-6bb59b37-de43-4843-b50b-6741f14b3fc3.png)

then it worked.
I will try dev branch without any EventTypes, thanks,
Regards,
Francine
