### ISSUE TITLE
Does not support IPv6 listening

### ISSUE THREAD

**Issue by pboyd04** [DMTF/Redfish-Event-Listener#12]
Currently this only binds to IPv4 sockets. If an IPv6 address is provided as the listening IP the code crashes.

**Comment by scottbusi** [comment]
Will IPv6 be supported at some point?

**Comment by mraineri** [comment]
It's still on our list, but unfortunately we've had higher priority items coming up. We can certainly bring this up in the group to discuss if we should bump up the priority of this tool.

**Comment by scottbusi** [comment]
Thank you for the quick response we made the following change and it seems to work
bindsocket = socket.socket()
to this:
bindsocket = socket.socket(family=socket.AF_INET6)
in RedfishEventListener_v1.py.

**Comment by mraineri** [comment]
Well that's good to hear! Does that allow for IPv4 simultaneously, or is it strictly IPv6 only?

**Comment by mraineri** [comment]
Also, if you do verify this continues to work for IPv4, would be willing to make a pull request with the fix?
