### ISSUE TITLE
StatusCode at RedfishEventListener_v1.py#L224 seems incorrect

### ISSUE THREAD

**Issue by cactusjiang** [DMTF/Redfish-Event-Listener#2]
At RedfishEventListener_v1.py#L224, the value of StatusCode will be returned.
> StatusCode = """HTTP/1.1 200 OK\r\n"""

However, in [RFC7230](https://tools.ietf.org/html/rfc7230#appendix-B), HTTP-message is defined as follows:
> HTTP-message = start-line *( header-field CRLF ) CRLF [ message-body]
> start-line = request-line / status-line
> status-line = HTTP-version SP status-code SP reason-phrase CRLF

It seems that the tool should return status-line + CRLF and therefore StatusCode should look like the following:
> StatusCode = """HTTP/1.1 200 OK\r\n\r\n"""

**Comment by billdodd** [comment]
Agreed. The overall HTTP-Message needs another CRLF.
