### ISSUE TITLE
Fail to create a subscription

### ISSUE THREAD

**Issue by vincent-tang1** [DMTF/Redfish-Event-Listener#20]
from tag 1.1.1, start from execution file, it will appear below error

Traceback (most recent call last):
  File "/root/Redfish-Event-Listener-1.1.1/RedfishEventListener_v1.py", line 260, in <module>
    my_ctx.login(auth=logintype.tolower())
AttributeError: 'str' object has no attribute 'tolower'

not sure if "tolower()" function should replace as "lower()", or we should use specific python version to support it ?
after made simple test to replace it to "lower()", as result, it is workable. thanks your attention

**Comment by mraineri** [comment]
You're certainly correct; we'll get a fix out ASAP.
