### ISSUE TITLE
Event Listener receiving same Redfish events

### ISSUE THREAD

**Issue by manipk01** [DMTF/Redfish-Event-Listener#25]
DMTF Redfish event listener is being ran on local machine. My observations are followed below.

**Observation:** 

- While receiving events from Redfish event listener it observed that system was repeating the same events after 1-2 mins.
- Because it gets into retrial mode(DeliveryRetryAttempts) due to absence of **content-length header** and **json response**. 
- Identified an issue about the response that is sending from the Redfish event listener does not contain the content-length header and the json response.

I checked in POST method section, https://github.com/DMTF/Redfish-Event-Listener/blob/master/RedfishEventListener_v1.py#L122-L123, Status code and "Connection: close" are sent as response only. 
If Response have "Content-length: "+str(len(bodydata))" and json.dumps(bodydata) message with status code and "Connection: close" with these changes, the events are not repeating it's working fine.

```
 res = "HTTP/1.1 200 OK\n" \
       "Connection: close\n" \
       "Content-length: "+str(len(bodydata)) + "\n" \
       "\n" + json.dumps(bodydata)
```
If i'm wrong. please let me know.

**Comment by mraineri** [comment]
Two things:

First, HTTP expects carriage return and new lines (not just new lines), so each line will need `\r\n`.

Second, I wouldn't expect the tool to echo the event data back to the service. However, I can understand why something needs to be sent back when a 200 OK is returned. Since we don't need to return anything, I think using 204 No Content would be cleaner.

Can you try with this?

```
                res = "HTTP/1.1 204 No Content\r\n" \
                      "Connection: close\r\n" \
                      "\r\n"
```

**Comment by manipk01** [comment]
It's working fine with your change. Will this change add in tool?

**Comment by mraineri** [comment]
We can certainly make that change in the tool. Do you want to make the pull request?

**Comment by plmanik** [comment]
Thanks for providing solution and verified from our side
If possible to make changes in tool, please proceed, else we can raise PR

Thanks,
Mani
