### ISSUE TITLE
Need support for non-SSL Events

### ISSUE THREAD

**Issue by JonHass** [DMTF/Redfish-Event-Listener#3]
Currently Redfish Event Listener only supports SSL POSTs of Redfish Events.  Request support for non-SSL Events sent by Redfish Mockup Server.  Whether Event Listener is listening for SSL or non-SSL POSTs should be configurable in the config.ini file.

**Comment by tomasg2012** [comment]
I think the Mockup Server can be tooled to send SSL events, it doesn't have to handle certificates in particular.  I imagine a piece of spec would require Events to be SSL for security reasons?

It may be dependent on the subscription URI whether or not SSL is used.
