### ISSUE TITLE
subscribing more than one server

### ISSUE THREAD

**Issue by El-H-git** [DMTF/Redfish-Event-Listener#7]
It is not possible to subscribe more than one server together.
They need to be subscribed one by one, before merging them in the ServerIPs part of the config.ini file

**Comment by mraineri** [comment]
I'm not entirely sure what you mean by this. ServerIPs lists the Redfish services to subscribe against, and thus the tool will create an EventDestination resource against each of the listed services.

**Comment by mraineri** [comment]
Closing; no updates for clarification. If more details can be provided and changes are needed, please reopen the issue.
